# Pipeline will be triggered based if the following are satisfied:
# - Any commits on any branch excluding 'prototype'
# - Tags on any branch
# - All pull requests

trigger:
  branches:
    include:
      - '*'
    exclude:
      - 'prototype/*'
  tags:
    include: 
       - '*'

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildVersion: '16.0'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: build
  displayName: 'Building SPIClient'
  steps:
      # restore nuget packages from solution
      - task: NuGetCommand@2
        displayName: 'Restore nuget solution'
        inputs:
          restoreSolution: '$(solution)'

      # build solution
      - task: VSBuild@1
        displayName: 'Build SPIClient'
        inputs:
          solution: '$(solution)'
          vsVersion: '$(buildVersion)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      # run visual studio unit tests
      - task: VSTest@2
        displayName: 'Run VSTests'
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      #condition: and(succeeded(), contains('$(Build.SourceBranch)', 'refs/tags/'))
      - task: NuGetCommand@2
        displayName: 'Package SPIClient'
        inputs:
            command: 'pack'
            packagesToPack: '.\SPIClient\SPIClient.csproj'
            configuration: '$(buildConfiguration)'    
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)/bin/SPIClient
          artifactName: SPIClient